basePath: /v1
definitions:
  invoice.Invoice:
    properties:
      fecha_creacion:
        type: string
      id:
        type: integer
      id_promotion:
        type: integer
      medicines:
        items:
          $ref: '#/definitions/medicine.Medicine'
        type: array
      pago_total:
        type: number
      promotion:
        $ref: '#/definitions/promotion.Promocion'
    type: object
  invoice.InvoiceRequest:
    properties:
      id_promotion:
        type: integer
      medicines:
        items:
          type: integer
        type: array
      pago_total:
        type: number
    type: object
  medicine.Medicine:
    properties:
      id:
        type: integer
      location:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  medicine.MedicineRequest:
    properties:
      location:
        type: string
      name:
        type: string
      price:
        type: number
    required:
    - location
    - name
    - price
    type: object
  models.HTTPResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  promotion.Promocion:
    properties:
      descripcion:
        type: string
      fecha_fin:
        type: string
      fecha_inicio:
        type: string
      id:
        type: integer
      porcentaje:
        type: number
    type: object
  promotion.PromocionRequest:
    properties:
      descripcion:
        example: Prueba
        type: string
      fecha_fin:
        example: "2021-12-07"
        type: string
      fecha_inicio:
        example: "2021-12-05"
        type: string
      porcentaje:
        example: 1.5
        maximum: 70
        type: number
    required:
    - descripcion
    - fecha_fin
    - fecha_inicio
    - porcentaje
    type: object
host: localhost:8081
info:
  contact:
    email: omar26begue@gmail.com
    name: Omar Isalgué Begue
  description: Back Aveonline
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Back Aveonline
  version: 1.0.0
paths:
  /invoice:
    get:
      consumes:
      - application/json
      description: Create the about information of the application.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/invoice.Invoice'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPResponse'
      summary: Invoice
      tags:
      - Invoice
    post:
      consumes:
      - application/json
      description: Create the about information of the application.
      parameters:
      - description: Invoice
        in: body
        name: about
        required: true
        schema:
          $ref: '#/definitions/invoice.InvoiceRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/invoice.Invoice'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPResponse'
      summary: Create
      tags:
      - Invoice
  /invoice/{start}/{end}:
    get:
      consumes:
      - application/json
      description: Create the about information of the application.
      parameters:
      - description: Start
        in: path
        name: start
        required: true
        type: string
      - description: End
        in: path
        name: start
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/invoice.Invoice'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPResponse'
      summary: Invoice
      tags:
      - Invoice
  /medicine:
    get:
      consumes:
      - application/json
      description: Create the about information of the application.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/medicine.Medicine'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPResponse'
      summary: Medicine
      tags:
      - Medicine
    post:
      consumes:
      - application/json
      description: Create the about information of the application.
      parameters:
      - description: Medicine
        in: body
        name: medicine
        required: true
        schema:
          $ref: '#/definitions/medicine.MedicineRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/medicine.Medicine'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPResponse'
      summary: medicine
      tags:
      - Medicine
  /promotion:
    get:
      consumes:
      - application/json
      description: Create the about information of the application.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/promotion.Promocion'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPResponse'
      summary: Promotion
      tags:
      - Promotion
    post:
      consumes:
      - application/json
      description: Create the about information of the application.
      parameters:
      - description: Promocion
        in: body
        name: promotion
        required: true
        schema:
          $ref: '#/definitions/promotion.PromocionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/promotion.Promocion'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.HTTPResponse'
      summary: Promotion
      tags:
      - Promotion
swagger: "2.0"
